Development/MeditechStaffing.Portal/MeditechStaffing.Portal/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeditechStaffing.Portal.Controllers
{
    public class FormsController : Controller
    {
        // GET: Forms
        public ActionResult Index()
        {
            return View();
        }
    }
}

Development/MeditechStaffing.Portal/MeditechStaffing.Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeditechStaffing.Portal.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        
    }
}

Development/MeditechStaffing.Portal/MeditechStaffing.Portal/Controllers/PoliciesAndProceduresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeditechStaffing.Portal.Controllers
{
    public class PoliciesAndProceduresController : Controller
    {
        // GET: PoliciesAndProcedures
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CommunityStaff()
        {
            return View();
        }

        public ActionResult BestPractices()
        {
            return View();
        }

    }
}

Development/MeditechStaffing.Portal/MeditechStaffing.Portal/Controllers/WhoswhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeditechStaffing.Portal.Controllers
{
    public class WhoswhoController : Controller
    {
        // GET: Whoswho
        public ActionResult Index()
        {
            return View();
        }
    }
}

Development/MeditechStaffing.Portal/MeditechStaffing.Portal/Views/Forms/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Forms</h4>
            <p class="category">List
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>File Name</th>
                        <th>File Type</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Hazard Report Form </td>
                        <td>Word Document</td>
                        <td><a href="~/Files/Forms/Hazard-Report-Form-v003-20140711.docx">View / Download</a> </td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Incident Report Form (Service Provider)</td>
                        <td>Word Document</td>
                        <td><a href="~/Files/Forms/Incident-Report-Form-(Service-Provider)-v007-20150109.docx">View / Download</a></td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>Incident Report Form (Service User)</td>
                        <td>Word Document</td>
                        <td><a href="~/Files/Forms/Incident-Report-Form-(Service-User)-v007-20150109.docx">View / Download</a></td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>Leave Form</td>
                        <td>PDF</td>
                        <td><a href="~/Files/Forms/Leave form.pdf">View / Download</a></td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>Staff Timesheet</td>
                        <td>PDF</td>
                        <td><a href="~/Files/Forms/Staff-timesheet-V003-20160418.pdf">View / Download</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Development/MeditechStaffing.Portal/MeditechStaffing.Portal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12" id="mainmenu-user">

    <div class="col-sm-4 text-center" id="mainmenu-user-PP">
        <div class="fa fa-info icon-circle font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Policies & <br>Procedures</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center" id="mainmenu-user-TR">
        <div class="fa fa-graduation-cap icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Training <br>Resources</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center" id="mainmenu-user-N">
        <div class="fa fa-newspaper-o icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">News<br>&nbsp;</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-wpforms icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Rosters<br>&nbsp;</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <a href="@Url.Action("Index", "Forms")">
        <div class="col-sm-4 text-center" id="mainmenu-user-F">
            <div class="fa fa-external-link-square icon-circle  font-meditech-red"></div>
            <h2 class="font-lt text-center home-title-ht">Forms<br>&nbsp;</h2>
            <p class="text-center home-blurb-ht"> </p>
            <p class="text-center">
                <button type="button" class="btn btn-danger btn-lg">Learn More</button>
            </p>
        </div>
    </a>

    <div class="col-sm-4 text-center">
        <div class="fa fa-address-book icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Who's Who<br>&nbsp;</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="whoswho.html"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

</div>


<!-- SUB MENU -->
<!-- Sub Menu Policies & Procedures -->
<div class="col-md-12" id="submenu-user-PP" style="display: none">

    <div class="col-sm-4 text-center">
        <div class="fa fa-info icon-circle font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Community<br>Staff</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-info icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Residential<br>Staff</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-info icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Best Practice <br>Principles</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center" id="submenu-user-PP-back">
        <div class="fa fa-arrow-left icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Back<br>&nbsp;</h2>
        <p class="text-center home-blurb-ht"> </p>

    </div>
</div> <!-- end Sub Menu Policies & Procedures -->
<!-- Sub Menu Training Resources -->
<div class="col-md-12" id="submenu-user-TR" style="display: none">

    <div class="col-sm-4 text-center">
        <div class="fa fa-graduation-cap icon-circle font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Support Worker <br>Induction</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-graduation-cap icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Registered Nurse <br>Induction</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-graduation-cap icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Occupational Health<br>& Safety</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-graduation-cap icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Manual<br>& Handling</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-graduation-cap icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Fire<br>& Evacuation</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-graduation-cap icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Wound<br>Management</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-graduation-cap icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Medication<br>Management</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-graduation-cap icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Diabetic car <br>& Management</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-graduation-cap icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Infection <br>Control</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center" id="submenu-user-TR-back">
        <div class="fa fa-arrow-left icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Back<br>&nbsp;</h2>
        <p class="text-center home-blurb-ht"> </p>

    </div>
</div><!-- end Sub Menu Training Resources -->
<!-- Sub Menu News -->
<div class="col-md-12" id="submenu-user-N" style="display: none">

    <div class="col-sm-4 text-center">
        <div class="fa fa-newspaper-o icon-circle font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Aged Care <br>&nbsp;</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-newspaper-o icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Disability <br>&nbsp;</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center">
        <div class="fa fa-newspaper-o icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Staff <br>&nbsp;</h2>
        <p class="text-center home-blurb-ht"> </p>
        <p class="text-center"><a href="#"><button type="button" class="btn btn-danger btn-lg">Learn More</button></a></p>
    </div>

    <div class="col-sm-4 text-center" id="submenu-user-N-back">
        <div class="fa fa-arrow-left icon-circle  font-meditech-red"></div>
        <h2 class="font-lt text-center home-title-ht">Back<br>&nbsp;</h2>
        <p class="text-center home-blurb-ht"> </p>

    </div>
</div> <!-- end Sub Menu News -->

Development/MeditechStaffing.Portal/MeditechStaffing.Portal/Views/PoliciesAndProcedures/BestPractices.cshtml
@{
    ViewBag.Title = "BestPractices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Community Staff</h4>
            <p class="category">List
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>File Name</th>
                        <th>File Type</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Abuse and Neglect</td>
                        <td>PDF</td>
                        <td><a href="~/Files/Policies-and-Procedures/Best Practices/Abuse-and-Neglect-v004-20170207.pdf">View / Download</a> </td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Anti Discrimination</td>
                        <td>Word Document</td>
                        <td><a href="~/Files/Policies-and-Procedures/Best Practices/Anti-Discrimination-V001-20130623.docx">View / Download</a></td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>Code of Conduct</td>
                        <td>PDF</td>
                        <td><a href="~/Files/Policies-and-Procedures/Best Practices/Code-of-Conduct-v006-20131231.pdf">View / Download</a></td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>Cultural Awareness</td>
                        <td>Word Document</td>
                        <td><a href="~/Files/Policies-and-Procedures/Best Practices/Cultural Awareness-V001-20130623.docx">View / Download</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Development/MeditechStaffing.Portal/MeditechStaffing.Portal/Views/PoliciesAndProcedures/CommunityStaff.cshtml
@{
    ViewBag.Title = "CommunityStaff";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Community Staff</h4>
            <p class="category">List
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>File Name</th>
                        <th>File Type</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Code of Conduct </td>
                        <td>PDF</td>
                        <td><a href="~/Files/Policies-and-Procedures/Community Staff/Code-of-Conduct-v006-20131231.pdf">View / Download</a> </td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Emergency Protocols</td>
                        <td>Word Document</td>
                        <td><a href="~/Files/Policies-and-Procedures/Community Staff/Emergency-Protocols-V002-20140623.docx">View / Download</a></td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>Home Care Common Standards</td>
                        <td>PDF</td>
                        <td><a href="~/Files/Policies-and-Procedures/Community Staff/home care common standards v14_0.pdf">View / Download</a></td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>Meditech Induction Handbook</td>
                        <td>PDF</td>
                        <td><a href="~/Files/Policies-and-Procedures/Community Staff/Meditech-Induction-Handbook-v007-20170526.pdf">View / Download</a></td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>Protecting Service User's Money and Property</td>
                        <td>PDF</td>
                        <td><a href="~/Files/Policies-and-Procedures/Community Staff/Protecting Service User's Money and Property-V002-20170207.pdf">View / Download</a></td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>Work Health and Safety</td>
                        <td>PDF</td>
                        <td><a href="~/Files/Policies-and-Procedures/Community Staff/Work-Health-and-Safety-v004-20170207.pdf">View / Download</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Development/MeditechStaffing.Portal/MeditechStaffing.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta name="viewport" content="width=device-width" />    
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    

    <title>@ViewBag.Title - Meditech Staffing Portal</title>
   
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/animate.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/light-bootstrap-dashboard.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/font-awesome-4.7.0/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("http://fonts.googleapis.com/css?family=Roboto:400,700,300")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/pe-icon-7-stroke.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/style-user.css")" rel="stylesheet" type="text/css" />
    
    @RenderSection("JavaScript", required: false)

    <!--     Fonts and icons     -->
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,700,300" rel="stylesheet" type="text/css">
   
	
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="black" data-image="@Url.Content("~/Content/img/sidebar.jpg")">

            <!--

                Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
                Tip 2: you can also add an image using data-image tag

            -->
            <div class="sidebar-wrapper">
                <div class="logo">


                    <img src="@Url.Content("~/Content/img/logo-meditech-transparent-big.png")" class="sidebar-logo">
                </div>

                <ul class="nav">

                    <li class="active">
                        <a href="@Url.Action("Index", "Home", new { area = "" })">
                            <i class="fa fa-dashboard"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>


                    <li>
                        <a href="#" data-toggle="collapse" data-target="#submenu-PP"><i class="fa fa-info"></i><p>Policies & Procedures <span class="caret"></span></p></a>
                    </li>
                    <ul id="submenu-PP" class="collapse nav sub-menu">
                        <li><a href="@Url.Action("CommunityStaff", "PoliciesAndProcedures")"> <p>Community Staff</p></a></li>
                        <li><a href="#"> <p>Residential Staff</p></a></li>
                        <li><a href="@Url.Action("BestPractices","PoliciesAndProcedures")"> <p>Best Practice Principles</p></a></li>
                    </ul>




                    <li>
                        <a href="#" data-toggle="collapse" data-target="#submenu-TR"><i class="fa fa-graduation-cap"></i><p>Training Resources <span class="caret"></span></p></a>
                    </li>
                    <ul id="submenu-TR" class="collapse nav sub-menu">
                        <li><a href="#"> <p>Support Worker Induction</p></a></li>
                        <li><a href="#"> <p>Registered Nurse Induction</p></a></li>
                        <li><a href="#"> <p>Occupational Health & safety</p></a></li>
                        <li><a href="#"> <p>Manual Handling</p></a></li>
                        <li><a href="#"> <p>Fire & Evacuation</p></a></li>
                        <li><a href="#"> <p>Wound Management</p></a></li>
                        <li><a href="#"> <p>Medication Management</p></a></li>
                        <li><a href="#"> <p>Diabetic Car & Management</p></a></li>
                        <li><a href="#"> <p>Infection Control</p></a></li>
                        <li><a href="#"> <p>Dementia Care</p></a></li>
                    </ul>

                    <li>
                        <a href="#" data-toggle="collapse" data-target="#submenu-N"><i class="fa fa-newspaper-o"></i><p>News <span class="caret"></span></p></a>
                    </li>
                    <ul id="submenu-N" class="collapse nav sub-menu">
                        <li><a href="#"> <p>Aged Care</p></a></li>
                        <li><a href="#"> <p>Disability</p></a></li>
                        <li><a href="#"> <p>Staff</p></a></li>
                    </ul>

                    <li>
                        <a href="index.html">
                            <i class="fa fa-external-link-square"></i>
                            <p>Rosters</p>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "Forms")"><i class="fa fa-wpforms"></i><p>Forms</p></a>
                    </li>
                    

                    <li>
                        <a href="@Url.Action("Index","Whoswho")">
                            <i class="fa fa-address-book"></i>
                            <p>Who's Who</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed bg-meditech-header">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h6><a class="navbar-brand" href="#">Dashboard</a></h6>
                    </div>
                    <div class="collapse navbar-collapse">

                        <ul class="nav navbar-nav navbar-right bg-agedcare">

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Welcome, Rod
                                    <img src="@Url.Content("~/Content/img/faces/profilepic-1.jpg")" class="img-circle avatar">
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Account</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Logout</a></li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>

            <div class="content">
                <div class="container-fluid">

                    <div class="row">
                        @RenderBody()

                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <p class="copyright pull-right">
                        &copy; 2017 Powered by <a href="#" class="font-meditech-orange">Collabor8 Digital</a>
                    </p>
                </div>
            </footer>
        </div>
    </div>



    <script type="text/javascript" src="@Url.Content("~/Content/js/jquery-1.10.2.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/bootstrap.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/bootstrap-checkbox-radio-switch.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/chartist.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/bootstrap-notify.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/light-bootstrap-dashboard.js")"></script>
    <script type="text/javascript">
        //Policies and Procedures
        document.getElementById("mainmenu-user-PP").addEventListener("click", function () {
            $("#mainmenu-user").hide(1000);
            $("#submenu-user-PP").show(1000);
        });
        document.getElementById("submenu-user-PP-back").addEventListener("click", function () {
            $("#submenu-user-PP").hide(1000);
            $("#mainmenu-user").show(1000);
        });

        //Traning Resources
        document.getElementById("mainmenu-user-TR").addEventListener("click", function () {
            $("#mainmenu-user").hide(1000);
            $("#submenu-user-TR").show(1000);
        });
        document.getElementById("submenu-user-TR-back").addEventListener("click", function () {
            $("#submenu-user-TR").hide(1000);
            $("#mainmenu-user").show(1000);
        });

        //News
        document.getElementById("mainmenu-user-N").addEventListener("click", function () {
            $("#mainmenu-user").hide(1000);
            $("#submenu-user-N").show(1000);
        });
        document.getElementById("submenu-user-N-back").addEventListener("click", function () {
            $("#submenu-user-N").hide(1000);
            $("#mainmenu-user").show(1000);
        });
        

        
    </script>


    @RenderSection("scripts", required: false)

</body>





</html>